services:
  app: 
    image: node:19
    command: > 
      sh -c 
      "npm install && 
      node node_modules/puppeteer/install.mjs && 
      apt-get update && 
      apt-get install -y libasound2 &&
      apt-get install -y libatk-bridge2.0-0 &&
      apt-get install -y libatk1.0-0 &&
      apt-get install -y libatspi2.0-0 &&
      apt-get install -y libc6 &&
      apt-get install -y libcairo2 &&
      apt-get install -y libcups2 &&
      apt-get install -y libdbus-1-3 &&
      apt-get install -y libdrm2 &&
      apt-get install -y libexpat1 &&
      apt-get install -y libgbm1 &&
      apt-get install -y libglib2.0-0 &&
      apt-get install -y libnspr4 &&
      apt-get install -y libnss3 &&
      apt-get install -y libpango-1.0-0 &&
      apt-get install -y libpangocairo-1.0-0 &&
      apt-get install -y libstdc++6 &&
      apt-get install -y libuuid1 &&
      apt-get install -y libx11-6 &&
      apt-get install -y libx11-xcb1 &&
      apt-get install -y libxcb-dri3-0 &&
      apt-get install -y libxcb1 &&
      apt-get install -y libxcomposite1 &&
      apt-get install -y libxcursor1 &&
      apt-get install -y libxdamage1 &&
      apt-get install -y libxext6 &&
      apt-get install -y libxfixes3 &&
      apt-get install -y libxi6 &&
      apt-get install -y libxkbcommon0 &&
      apt-get install -y libxrandr2 &&
      apt-get install -y libxrender1 &&
      apt-get install -y libxshmfence1 &&
      apt-get install -y libxss1 &&
      apt-get install -y libxtst6 &&
      npm start"
    ports:
      - 127.0.0.1:3000:3000
    working_dir: /app
    volumes:
      - ./:/app
