services:
  app: 
    image: node:19
    command: > 
      sh -c 
      "npm install && 
      node node_modules/puppeteer/install.mjs && 
      apt-get update && apt-get install -y 
      libasound2 
      libatk-bridge2.0-0 
      libatk1.0-0 
      libatspi2.0-0 
      libc6 
      libcairo2 
      libcups2 
      libdbus-1-3 
      libdrm2 
      libexpat1 
      libgbm1 
      libglib2.0-0 
      libnspr4 
      libnss3 
      libpango-1.0-0 
      libpangocairo-1.0-0 
      libstdc++6 
      libuuid1 
      libx11-6 
      libx11-xcb1 
      libxcb-dri3-0 
      libxcb1 
      libxcomposite1 
      libxcursor1 
      libxdamage1 
      libxext6 
      libxfixes3 
      libxi6 
      libxkbcommon0 
      libxrandr2 
      libxrender1 
      libxshmfence1 
      libxss1 
      libxtst6 && 
      npm start"
    ports:
      - 127.0.0.1:3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    volumes:
      - avandra-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

volumes:
  avandra-mysql-data:
